spring:
  datasource:
    url: jdbc:mysql://35.178.45.24:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format-sql: true

      # Get Hibernate to generate drop & create scripts in project root
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: drop-and-create
#              create-target: guru_database_create.sql
#              drop-target: guru_database_drop.sql
